version: '3'

services:
  operations-api:
    container_name: 'operations-api'
    image: 'ghcr.io/tricolor-austral/ingsis-operations:latest'
    ports:
      - "8083:8080"
    depends_on:
      - operations_db
    environment:
      DB_HOST: operations_db
      DB_PORT: 5432
      DB_NAME: printscript-operations
      DB_USER: postgres
      DB_PASSWORD: postgres

  operations_db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=printscript-operations
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - operations_volume:/var/lib/postgresql/data

  snippet-runner-api:
    container_name: 'snippet-runner-api'
    image: 'ghcr.io/tricolor-austral/ingsis-snippetrunner:latest'
    ports:
      - "8081:8080"
    environment:
      DB_HOST: snippet_runner_db
      DB_PORT: 5432
      DB_NAME: printscript-snippet-runner
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - snippet_runner_db

  snippet_runner_db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=printscript-snippet-runner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - snippetrunner_volume:/var/lib/postgresql/data

  permission-api:
    container_name: 'permission-api'
    image: 'ghcr.io/tricolor-austral/ingsis-permission:latest'
    ports:
      - "8082:8080"
    environment:
      DB_HOST: permission_db
      DB_PORT: 5432
      DB_NAME: printscript-permission
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - permission_db

  permission_db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=printscript-permission
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - permission_volume:/var/lib/postgresql/data

volumes:
  operations_volume:
  permission_volume:
  snippetrunner_volume:
