version: '3'

services:
  printscript-ui:
      container_name: 'printscript-ui'
      image: 'ghcr.io/tricolor-austral/printscript-ui:latest'
      ports:
        - "5173:5173"

  operations-api:
      container_name: 'operations-api'
      image: 'ghcr.io/tricolor-austral/ingsis-operations:latest'
      ports:
        - "8083:8080"
      depends_on:
        - operations_db
      environment:
        DB_HOST: operations_db
        DB_PORT: 5432
        DB_NAME: printscript-operations
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}

  operations_db:
      image: 'postgres:alpine'
      environment:
        - POSTGRES_DB=printscript-operations
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      expose:
        - "5432"
      volumes:
        - operations_volume:/var/lib/postgresql/data

  snippet-runner-api:
      container_name: 'snippet-runner-api'
      image: 'ghcr.io/tricolor-austral/ingsis-snippetrunner:latest'
      ports:
        - "8081:8080"

  permission-api:
      container_name: 'permission-api'
      image: 'ghcr.io/tricolor-austral/ingsis-permission:latest'
      ports:
        - "8082:8080"
      environment:
        DB_HOST: permission_db
        DB_PORT: 5432
        DB_NAME: printscript-permission
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
      depends_on:
        - permission_db

  permission_db:
      image: 'postgres:alpine'
      environment:
        - POSTGRES_DB=printscript-permission
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      expose:
        - "5432"
      volumes:
        - permission_volume:/var/lib/postgresql/data
  proxy:
    container_name: 'reverse-proxy-dev'
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
        - duckdns
#        - certbot
        - printscript-ui
        - operations-api
        - snippet-runner-api
        - permission-api
        - operations_db
        - permission_db
  duckdns:
    image: lscr.io/linuxserver/duckdns:version-d63af1c1
    container_name: duckdns
    environment:
      - SUBDOMAINS=tricolor-austral
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
  certbot:
    container_name: "certbot"
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email marco.castagnaro@ing.austral.edu.ar -d tricolor-austral.duckdns.org --agree-tos

volumes:
    operations_volume:
    permission_volume:
    snippetrunner_volume:
