version: '3'

services:
  proxy:
    container_name: 'reverse-proxy-dev'
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./static/:/usr/share/nginx/html:ro
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    #echo "test" | sudo tee /var/www/certbot/.well-known/acme-challenge/test
  #curl http://tricolor-austral.duckdns.org/.well-known/acme-challenge/test

