name: Deploy to Azure VM

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          DEVVM_KEY: ${{ secrets.INGSIS_DEV_KEY }}
          GH_TOKEN: ${{ secrets.DOCKER_PACKAGES_SECRET }}
        run: |
          echo "$DEVVM_KEY" > dev_key.pem
          echo "$GH_TOKEN" > GH_TOKEN
          chmod 400 dev_key.pem

      - name: Run deploy script
        run: |
          ./deployDevVm.sh
