name: Deploy to Azure Production Vm


on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Deployement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD}}
          username: "tricolor-ingsis"
          key: ${{ secrets.INGSIS_PROD_KEY}}
          script: |
            cd ingSis-microservices
            sudo docker compose -f docker-compose.prod.yml stop
            sudo git pull
            sudo docker compose -f docker-compose.prod.yml up -d --build
