name: Deploy to Azure VM

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Set up SSH key
#        env:
#          DEVM_KEY: ${{ secrets.INGSIS_DEV_KEY }}
#          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
#
#        run: |
#          echo "$DEVM_KEY" > dev_key.pem
#          echo "$GH_TOKEN" > git_token

      - name: Update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: "snippet-searcher-admin"
          key: ${{ secrets.INGSIS_DEV_KEY }}
          script: |
            cd ingSis-microservices
            docker compose -f docker-compose.dev.yml stop
            docker compose -f docker-compose.dev.yml up --build
