name: Deploy to Azure VM

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          DEVM_KEY: ${{ secrets.INGSIS_DEV_KEY }}
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}

        run: |
          echo "$DEVM_KEY" > dev_key.pem
          echo "$GH_TOKEN" > git_token

      - name: Run deploy script
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          ./deployDev.sh
          echo "VERSION 1.01"
