name: Deploy to VM

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.INGSIS_DEV_KEY }}

      - name: Set up Git for GitHub Actions
        run: |
          git config --global url."https://${{ env.GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - name: Deploy to VM
        env:
          SSH_HOST: "tricolor-ingsis@4.203.104.146"
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_HOST << 'EOF'
            cd ingSis-microservices
            git pull
            docker compose up --build -d
          EOF
